export { default as Logo } from './Logo'
export { default as Notice } from './Notice'
export { default as School } from './School'
export { default as Search } from './Search'
export { default as Etc } from './Etc'
